- shell:
    cmd: |
        set -e
        set -x
        GATE_STACK_USER={{ ansible_user }}
        IS_GATE=True

        BASE_DIR={{ base_dir }}
        GATE_DEST={{ gate_dest_dir }}
        PROJECT_NAME={{ project_name }}
        NEUTRON_DIR={{ neutron_dir }}
        DEVSTACK_PATH={{ devstack_dir }}
        TOP_DIR={{ devstack_dir }}
        VENV={{ tests_venv }}
        STACK_USER=stack
        OVS_BRANCH={{ OVS_BRANCH }}
        OVN_BRANCH={{ OVN_BRANCH }}
        Q_BUILD_OVS_FROM_GIT={{ Q_BUILD_OVS_FROM_GIT }}

        source $DEVSTACK_PATH/functions
        source $DEVSTACK_PATH/lib/neutron_plugins/ovn_agent
        source $NEUTRON_DIR/tools/configure_for_func_testing.sh

        configure_host_for_func_testing
    executable: /bin/bash
