- hosts: all
  roles:
    - run-devstack
    # Run bindep and test-setup after devstack so that they won't interfere
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - role: ensure-tox
      vars:
        ensure_tox_version: "<4"
    - tox
